/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
 // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
Success: [{type: 'autogenerated', dirName: '01_Success_Mantras'}],  // foldername
Success_Pillars: [{type: 'autogenerated', dirName: '02_Success_Pillars'}],  // foldername
Lifestyle: [{type: 'autogenerated', dirName: '03_Lifestyle'}],  // foldername
Health: [{type: 'autogenerated', dirName: '04_Health'}],  // foldername
Finance: [{type: 'autogenerated', dirName: '05_Finance'}],  // foldername
Studies: [{type: 'autogenerated', dirName: '06_Studies'}],  // foldername
Career: [{type: 'autogenerated', dirName: '07_Career'}],  // foldername
Success_Temp: [{type: 'autogenerated', dirName: '110_Success_Temp'}],  // foldername
Language: [{type: 'autogenerated', dirName: '170_Language'}],  // foldername
mgmt: [{type: 'autogenerated', dirName: '180_MGMT'}],  // foldername
temp: [{type: 'autogenerated', dirName: 'temp'}],  // foldername
//    newtwo: [{type: 'autogenerated', dirName: 'newthree'}],  // foldername

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
   
  
//  successSidebar: [
//    'intro',
//    {
//      type: 'category',
//      label: 'Success',
//      items: ['tutorial-basics/create-a-document'],
//    },
//  ],
  
   
};

export default sidebars;
